### ISSUE TITLE
posting link should use meta tags to embed picture and subtitle

### ISSUE THREAD

**Issue by whatisgalen** [bubbleboy14/ctnet#2]
desired functionality is something like:
user pastes link to article, image, caption, and subtitle become embedded as the post on the newsfeed/stream automatically a la facebook.

**Comment by bubbleboy14** [comment]
Request handler:

https://github.com/bubbleboy14/ctnet/commit/1c6b8eadce0a8556c52c29ffd1698f9e23d8dda2

Button/prompt:

https://github.com/bubbleboy14/ctnet/commit/5064c479d34a7593b668418c4965b2e9976f7d90

So CAN.widget.stream.addNodes(), which the Community Page uses in several sections including the Thought Stream, now adds an extra button, "Embed Link", below the text area. When clicked, this button triggers a prompt asking you for a link. When you give it a link, it populates the text area with "[title] [image] [link]", leaving room for your own comment underneath.

Tested and works with: SF Chronicle, SF Examiner, CBS Local (SF), Al Jazeera, CNN, MSNBC, Natural News, Truth Stream Media, Democracy Now, Washington Post, New York Times, USA Today, SFist, SF Gate, Kron4, and the Oakland Press.
